### ISSUE TITLE
Ausscheiden aus dem E-Mail Verteiler

### ISSUE THREAD

**Issue by Antujin** [fsphys-muenster/ordnungen#2]
In der Fachschafts GO sollte unter §9 ein Passus rein, der klärt unter welchen Bedingungen Leute, die nach Ausscheiden auf dem Verteiler bleiben, von diesem entfernt werden können.
Z.B. 2 Jahre nach Ausscheiden werden Leute entfernt, oder zu jedem Semester wird geschaut wer bleiben darf.

**Comment by l-althueser** [comment]
Aktueller Status? ;)

**Comment by Antujin** [comment]
Ich überlege noch wie ich das Formulieren soll. Das soll nicht zu hart aber auch nicht zu lasch sein.
Außerdem hat es zeit bis zur nächsten FSV Sitzung

**Comment by Antujin** [comment]
Erledigt. siehe letzter Commit
