### ISSUE TITLE
Formulierung zur formalen Veröffentlichung des Protokolls

### ISSUE THREAD

**Issue by l-althueser** [fsphys-muenster/ordnungen#3]
> Wie angekündigt beantragt Maik eine Änderung der GO. Der bisherige § 6 Abs. 4:
> 
> „Der öffentliche Teil eines Protokolls wird im Fachschaftsraum ausgehängt und auf
> dem Netzlaufwerk des FSR archiviert. Eine Veröffentlichung auf den Internetseiten
> der Fachschaft ist möglich.“
> 
> soll durch folgende Fassung ersetzt werden:
> 
> „Das Protokoll wird auf dem Netzlaufwerk des FSR archiviert. Der öffentliche Teil
> des Protokolls wird, für alle Physik-Studierenden zugänglich, auf den Internetseiten
> der Fachschaft veröffentlicht.“

Diese Änderung wurde in der Form abgelehnt.

**Comment by Antujin** [comment]
Ich würde behaupten das ist erledigt :P
